### ISSUE TITLE
HTML5 media control is broken

### ISSUE THREAD

**Issue by Lastrik** [AInoob/NooBox#7]
HTML5 media control functionality is completely broken and messes on pages that don't have any video by cancelling keystrokes on some places. I'd also argue that a functionality like should be opt-in and not opt-out as it currently is because it has nothing to do with what the base extension does (I lost 20 minutes figuring out which extension was messing with my browser)

**Comment by AInoob** [comment]
Hello there, you are totally right that HTML5 Video Control should be opt-in rather than opt-out, and it is! https://github.com/AInoob/NooBox/blob/master/src/background/background.js#L104
By default it's disabled, the reason that it was running is because you turned it on before.

I have the same problem that on some website where the HTML5 Video is set as background, I cannot type in anything, to avoid that, you can either turn of HTML5 Video Control or close it on current website, by clicking the Sun icon on NooBox.

**Comment by Lastrik** [comment]
Yep You're right I did. Sorry for this

**Comment by AInoob** [comment]
No problem, personally I do not think HTML5 Video Control is ready yet. Just as you said, it prevent's you from doing things. Sometimes I cannot type on websites because HTML5 Video Control~ LOL
